########################
# Kubernetes Service for GlobalSend app
# - Type and port configurable via Helm values
# - Routes traffic to pods labeled 'app: globalsend'
# - TargetPort fixed at 80
########################
apiVersion: v1
kind: Service
metadata:
  name: globalsend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: globalsend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80